name: Generate changelog

on:
    push:
        branches:
            - main
#    schedule:
#        - cron: '22 */3 * * *'

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Get Date
              id: get-date
              run: |
                echo "::set-output name=date::$(/bin/date -u "+%s")"
              shell: bash
            - uses: actions/cache@v2
              with:
                path: ~/repos
                key: init-2020-06-16-repos-${{ steps.get-date.outputs.date }}
                restore-keys: init-2020-06-16-repos-
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pyyaml lxml
            - name: Add static content to output
              run: |
                mkdir -p output
                cp -r static/* output
            - name: Create weekly changelog
              run: |
                mkdir -p output/weekly
                python git_changelog.py --weekly > output/weekly/index.html
            - name: Create release changelog
              run: |
                mkdir -p output/release
                python git_changelog.py --release > output/release/index.html
            - name: Deploy to GitHub Pages
              if: success()
              uses: crazy-max/ghaction-github-pages@v2
              with:
                target_branch: gh-pages
                build_dir: output
                jekyll: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
